### ISSUE TITLE
Support for running within Docker

### ISSUE THREAD

**Issue by jmuchovej** [zerotier/zeronsd#12]
👋  Coming over from Reddit. 😅  (I put together [ZeroDNS](https://github.com/jmuchovej/zerodns).)

ZeroNS appears to resolve one of my goals with ZeroDNS – name resolution of ZeroTier peers. However, the other goal seems unsolved: allowing a Docker Compose stack to make use of said name resolution.

Maybe this is my networking ignorance showing – but would it make sense to have an edition of ZeroNS that runs within a Docker container, as well?

e.g. I currently have a few compose stacks that use a ZeroDNS container as their network router (via `networks: ["container:zerodns"]`, or equivalent).

(May also be worth noting this is without setting up ZeroNS locally – I won't be able to get to this for a few days.)

(Also, I'm willing to take this up in the future; just inquiring at the moment.)

**Comment by erikh** [comment]
Thanks for the report! So, running in a container is tricky because our container story is not very good, but the good news is that it's being worked on.

To do this effectively you just need to bring in the TAP interface and make sure that `zerotier-one` is reachable over the container's networking stack, which more or less means `--net host` at the moment.

That said, we are trying to get https://github.com/zerotier/libzt in a place where `zerotier-one` is not necessary to  run zeronsd. that will take some time.

Until then, try out the dockerfiles in the master branch of https://github.com/zerotier/ZeroTierOne and see if they help you get closer to your goal.

Hope this was useful context! Please leave this ticket open. Thanks!

**Comment by erikh** [comment]
Hey @jmuchovej,

I setup a dockerfile. We'll get to a release soon, but check it out please if you get time and tell me what you think of it; instructions on use are in the top-level readme.

I'll leave this open until I get a deeper chance to use it, or I get some confirmation it's working smoothly for others.

**Comment by erikh** [comment]
Closing this as it seems to work.

**Comment by jmuchovej** [comment]
I might have missed something in the docs, but this doesn't appear to work...

Here's what I've been using:
```yaml
version: "3.8"

services:
  zerons:
    image: zerotier/zeronsd:latest
    network_mode: "host"
    volumes:
      - "/Library/Application Support/ZeroTier/One:/var/lib/zerotier-one:ro"
    environment:
      ZEROTIER_CENTRAL_TOKEN: <redacted>
    command: "start -d <domain> <network-id>"
```

The container fails to even start. 👀  (The `command` doesn't override `help` as you have in the `Dockerfile`.) I also don't see any output when running the same as a `docker run --rm ...` command.
