### ISSUE TITLE
Error: failed to parse header value

### ISSUE THREAD

**Issue by danielskapunk** [zerotier/zeronsd#200]
Cant start zeronsd

```
sudo /usr/bin/zeronsd start -l trace -t /home/daniel/zttoken -d lan af415e486f4e4b3
Dec 01 13:23:43.601  INFO zeronsd::init: Welcome to ZeroNS!
Error: failed to parse header value
```
running in a VM
OS: Ubuntu 22.04.1 LTS x86_64 
Kernel: 5.15.0-53-generic

**Comment by anhdowastaken** [comment]
Same to me. This is my docker-compose file:
```
services:
  zerotier:
    image: zerotier/zerotier:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: host
    devices:
      - /dev/net/tun:/dev/net/tun
    command: xxxxxxxxxxxxxxxx
    volumes:
      - /opt/appdata/zerotier-one/authtoken.secret:/var/lib/zerotier-one/authtoken.secret
      - /opt/appdata/zerotier-one/identity.public:/var/lib/zerotier-one/identity.public
      - /opt/appdata/zerotier-one/dentity.secret:/var/lib/zerotier-one/identity.secret
    environment:
      - TZ=Asia/Ho_Chi_Minh

  dns:
    image: zerotier/zeronsd:latest
    restart: unless-stopped
    depends_on:
      - zerotier
    network_mode: host

    command: start xxxxxxxxxxxxxxxx
    volumes:
      - /opt/appdata/zerotier-one/authtoken.secret:/var/lib/zerotier-one/authtoken.secret:ro
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ZEROTIER_CENTRAL_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
